name: Docker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
          echo 'DATABASE_URL="${{ secrets.DATABASE_URL }}"' >> .env
          echo 'NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}"' >> .env
          echo 'NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}"' >> .env
          echo 'AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"' >> .env
          echo 'AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"' >> .env
          echo 'AWS_REGION="${{ secrets.AWS_REGION }}"' >> .env
          echo 'AWS_BUCKET_NAME="${{ secrets.AWS_BUCKET_NAME }}"' >> .env
          echo 'NEXT_PUBLIC_API_URL="${{ secrets.NEXT_PUBLIC_API_URL }}"' >> .env

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: aleksipam/carshop:latest
